Add item requests
AlinaProvotorova/java-shareit pull request #5
Opened 2023-08-18 14:16 UTC by AlinaProvotorova

2023-08-19 14:01 UTC, z8q requested changes

2023-08-19 14:01 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public ItemRequestDto create(
создаю пользователя 1 и 2, 
и несколько запросов (POST http://localhost:8080/requests/) от 1-го пользователя, 
получаю ответы:
```JSON
{
	"id": 1,
	"description": "car",
	"created": "2023-08-19T17:14:11.266504"
}
```
и 
```JSON
{
	"id": 2,
	"description": "snowboard",
	"created": "2023-08-19T17:14:35.223865"
}
```
далее создаю вещь от пользователя 1 с requestedId 1:
```JSON
{
	"name": "car",
	"description": "Tesla",
	"available": true,
	"requestId": 1
}
```
Далее делаю запрос GET http://localhost:8080/requests
и получаю ответ, где поле items заполняется для всех запросов, хотя по тз должно заполнится только для запроса с id = 1
```JSON
[
	{
		"id": 1,
		"description": "car",
		"created": "2023-08-19T17:14:11.266504",
		"items": [
			{
				"id": 1,
				"name": "car",
				"description": "Tesla",
				"available": true,
				"lastBooking": null,
				"nextBooking": null,
				"requestId": 1,
				"comments": null
			}
		]
	},
	{
		"id": 2,
		"description": "snowboard",
		"created": "2023-08-19T17:14:35.223865",
		"items": [
			{
				"id": 1,
				"name": "car",
				"description": "Tesla",
				"available": true,
				"lastBooking": null,
				"nextBooking": null,
				"requestId": 1,
				"comments": null
			}
		]
	}
]
```

2023-08-19 14:01 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public List<ItemRequestResponseDto> getAll(
Создаю пять запросов пользователем 1,
и пытаюсь посмотреть их пользователем 2
когда запрашиваю все пять, выводит верно
`GET http://localhost:8080/requests/all?from=0&size=5`
```JSON
[
	{
		"id": 5,
		"description": "snowboard5",
		"created": "2023-08-19T17:20:24.483778",
		"items": []
	},
	{
		"id": 4,
		"description": "snowboard4",
		"created": "2023-08-19T17:20:21.555428",
		"items": []
	},
	{
		"id": 3,
		"description": "snowboard3",
		"created": "2023-08-19T17:20:18.815959",
		"items": []
	},
	{
		"id": 2,
		"description": "snowboard2",
		"created": "2023-08-19T17:20:16.094313",
		"items": []
	},
	{
		"id": 1,
		"description": "snowboard",
		"created": "2023-08-19T17:19:44.954298",
		"items": []
	}
]
```
Теперь пробую вывести только запросы с id 5 и 4
`GET http://localhost:8080/requests/all?from=0&size=2`
```JSON
[
	{
		"id": 5,
		"description": "snowboard5",
		"created": "2023-08-19T17:20:24.483778",
		"items": []
	},
	{
		"id": 4,
		"description": "snowboard4",
		"created": "2023-08-19T17:20:21.555428",
		"items": []
	}
]
```
Все верно, теперь пробуем только 4 и 3
По логике, запрос должен быть такой
`GET http://localhost:8080/requests/all?from=1&size=2`
Но ответ следующий:
```JSON
[
	{
		"id": 3,
		"description": "snowboard3",
		"created": "2023-08-19T17:20:18.815959",
		"items": []
	},
	{
		"id": 2,
		"description": "snowboard2",
		"created": "2023-08-19T17:20:16.094313",
		"items": []
	}
]
```
А если запросить только 4-й:
`GET http://localhost:8080/requests/all?from=1&size=1`
Тут снова все правильно:
```JSON
[
	{
		"id": 4,
		"description": "snowboard4",
		"created": "2023-08-19T17:20:21.555428",
		"items": []
	}
]
```
стоит проверить работу пагинации

2023-08-19 14:01 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            throw new EmailDuplicateException(
Есть блоки catch, которые не протестировали. Возьмем этот, как пример.
Этот блок, как я понял, должен срабатывать, если мы попробуем дважды сохранить пользователя с одинаковым email. Но когда я это делаю, я получаю ошибку 500:
```JSON
{
	"timestamp": "2023-08-19T13:52:03.531+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/users/"
}
```
Потому что на самом деле тут приходит не ConstraintViolationException, а DataIntegrityViolationException.
Если попробуем отлавливать ее, то при попытке сохранения дубля получим корректный ответ:
```JSON
{
	"error": "Email bob@yandex.ru уже существует. Запрос отклонен"
}
```
Поэтому блоки catch тоже стоит тестировать)

2023-08-21 09:00 UTC, AlinaProvotorova commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public List<ItemRequestResponseDto> getAll(
не совсем понимаю вопроса, from это номер страницы size длина страницы. Если мы задаем параметря size = 2, то первая страница(она же 0) содержит данные id=5 и id =4, а если запрашиваем вторую страницу то будет содержать данные id=3 и id =2, т.е раюота пагинации верная

2023-08-21 09:01 UTC, AlinaProvotorova commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            throw new EmailDuplicateException(
хорошо учту, по тз было 90% покрытия кода, я это выполнила

2023-08-22 13:36 UTC, TyutterinYakov reviewed
Добрый день! Прошу прощения за задержку) Работа не сразу попала ко мне) Отметил то, что важно исправить и то, что можно улучшить - "(предложение)". Хорошего дня! Если возникнут вопросы оп ревью - пиши в пачку, буду рад помочь🌅

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@EqualsAndHashCode
Перед с использованием аннотаций для автоматической генерации кода в классах-сущностях - хорошо было бы ознакомиться со статьей)
https://habr.com/ru/company/haulmont/blog/564682/

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(defaultValue = "0", required = false) @PositiveOrZero int from,
Если указано `defaultValue`, это уже подразумевает, что параметр не является обязательным, следовательно `required = false` не требуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(defaultValue = "0", required = false) @PositiveOrZero int from,
Если указано `defaultValue`, это уже подразумевает, что параметр не является обязательным, следовательно `required = false` не требуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +@Repository
Аннотация `@Repository` не имеет смысла, так как наследуясь от `JpaRepository` мы уже объявляем бин)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        BookingValidate.validateBookingRequest(bookingRequest, item, user);
(предложение)Эту валидацию можно было бы реализовать с помощью аннотации валидации над классом, чтобы поддерживать декларативный подход https://devcolibri.com/spring-mvc-кастомная-аннотация-для-валидации/
Кстати, если будет интересно то, как реализовать кастомную аннотацию валидации на уровне класса `BookingRequestDto` - можешь чекнуть тут) https://github.com/TyutterinYakov/CustomValidationClassLevel Я написал небольшой примерчик, чтобы было проще разобраться в теме

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
Для `state` хорошо было бы ввести Enum

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
Для `state` хорошо было бы ввести Enum
Чтобы случайно не ошибиться в именовании и в случае изменений - произвести их в одном месте)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingValidate.java
> +        if (bookingRequest.getStart().isBefore(LocalDateTime.now())) {
Не требуется, так как эта проверка реализована с помощью аннотаций валидации в DTO)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingValidate.java
> +public class BookingValidate {
(предложение)Можно добавить такую аннотацию
`@NoArgsConstructor(access = AccessLevel.PRIVATE)` или [`@UtilityClass`](https://projectlombok.org/features/experimental/UtilityClass)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)
Кстати, при использовании второй, даже `static` использовать не потребуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +public class BookingMapper {
(предложение)Можно добавить такую аннотацию
`@NoArgsConstructor(access = AccessLevel.PRIVATE)` или [`@UtilityClass`](https://projectlombok.org/features/experimental/UtilityClass)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)
Кстати, при использовании второй, даже `static` использовать не потребуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +public class BookingResponseDto {
Действительно ли в этом классе требуются аннотации валидации?) Если я не ошибаюсь, то он выступает только в качестве возвращаемого значения, и оно никак не валидируется

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingShortDto.java
> +public class BookingShortDto {
Действительно ли в этом классе требуются аннотации валидации?) Если я не ошибаюсь, то он выступает только в качестве возвращаемого значения, и оно никак не валидируется

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +@Repository
Аналогично, аннотация не требуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/Item.java
> +@ToString
Перед использованием аннотаций для автоматической генерации кода в классах-сущностях - хорошо было бы ознакомиться со статьей)
https://habr.com/ru/company/haulmont/blog/564682/

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestParam(defaultValue = "0", required = false) @PositiveOrZero int from,
Кстати, для того, чтобы эти аннотации стали учитываться, необходимо над классом навесить аннотацию `@Validated`. Но выбрасываться будет не `MethodArgumentNotValidException`, к которому мы привыкли, а `ConstraintViolationException`

Если указано `defaultValue`, это уже подразумевает, что параметр не является обязательным, следовательно `required = false` не требуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestParam(defaultValue = "0", required = false) @PositiveOrZero int from,
Кстати, для того, чтобы эти аннотации стали учитываться, необходимо над классом навесить аннотацию `@Validated`. Но выбрасываться будет не `MethodArgumentNotValidException`, к которому мы привыкли, а `ConstraintViolationException`

Если указано `defaultValue`, это уже подразумевает, что параметр не является обязательным, следовательно `required = false` не требуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                         @RequestHeader(value = "X-Sharer-User-Id") @Positive Long userId,
Для заголовка у нас введена отдельная константа) Хорошо было бы использовать ее и здесь)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +@Component
Аннотация не требуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/CommentMapper.java
> +public class CommentMapper {
(предложение)Можно добавить такую аннотацию
`@NoArgsConstructor(access = AccessLevel.PRIVATE)` или [`@UtilityClass`](https://projectlombok.org/features/experimental/UtilityClass)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)
Кстати, при использовании второй, даже `static` использовать не потребуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/CommentResponseDto.java
> +public class CommentResponseDto {
Действительно ли в этом классе требуются аннотации валидации?) Если я не ошибаюсь, то он выступает только в качестве возвращаемого значения, и оно никак не валидируется

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +public class CommentDto {
При создании нам требуется лишь поле `text`, остальные хорошо было бы исключить, чтобы работать лишь с теми данными, что требуются)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private User author;
Классы-DTO не должны содержать в себе сложные объекты по типу классов-сущностей. Мы всегда должны контролировать те данные, что получаем и отдаем. Не только в целях безопасности, но и производительности, так как зачем тратить ресурсы на передачу тех данных, что не будут использоваться

Но это поле не требуется и его можно исключить)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +public class CommentDto {
Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`. Эта аннотация удобна тем, что допускает null, за счет чего при обновлении по значению мы сможем понять, было передано значение или нет)

Но, чтобы не производить разбиение на отдельные классы для обновления и создания, можно было бы использовать валидацию по группам)
https://struchkov.dev/blog/ru/spring-boot-validation/

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>      private Boolean available;
Здесь, например, будет использоваться `@NotNull(groups = Create.class)`
Таким образом, что она должна учитываться лишь при `@Validated(Create.class)` перед параметром метода в контроллере)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
>  public class ItemMapper {
(предложение)Можно добавить такую аннотацию
`@NoArgsConstructor(access = AccessLevel.PRIVATE)` или [`@UtilityClass`](https://projectlombok.org/features/experimental/UtilityClass)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)
Кстати, при использовании второй, даже `static` использовать не потребуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemResponseDto.java
> +public class ItemResponseDto {
Действительно ли в этом классе требуются аннотации валидации?) Если я не ошибаюсь, то он выступает только в качестве возвращаемого значения, и оно никак не валидируется

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemResponseDto.java
> +    public static ItemResponseDto create(Booking lastBooking, Booking nextBooking, Item item, List<Comment> comments) {
Эта логика должна находиться не внутри класса-DTO, а внутри маппера) Так как преобразованиями занимается он)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +            @RequestParam(defaultValue = "0", required = false) @PositiveOrZero int from,
Кстати, для того, чтобы эти аннотации стали учитываться, необходимо над классом навесить аннотацию `@Validated`. Но выбрасываться будет не `MethodArgumentNotValidException`, к которому мы привыкли, а `ConstraintViolationException`

Если указано `defaultValue`, это уже подразумевает, что параметр не является обязательным, следовательно `required = false` не требуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +public class ItemRequestMapper {
(предложение)Можно добавить такую аннотацию
`@NoArgsConstructor(access = AccessLevel.PRIVATE)` или [`@UtilityClass`](https://projectlombok.org/features/experimental/UtilityClass)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)
Кстати, при использовании второй, даже `static` использовать не потребуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      }
Кстати, вместо `@Valid` можно использовать такую аннотацию `@Validated(Create.class)`. Таким образом мы указываем, какую группу аннотаций следует учитывать. `Create` - это интерфейс, который ты создаешь самостоятельно, он будет пустым и служит лишь для указания группы) Аналогично следует поступить при обновлении, но там будет аннотация `@Validated(Update.class)`

Если не использовать валидацию по группам, тогда потребуется при обновлении дополнительно проверять формат переданной строки с почтой в коде, что не очень удобно. Либо же потребуется ввести отдельный класс DTO для обновления, чтобы над полем с почтой использовать `@Email`

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
>  public class UserDto {
Так же и здесь, можно было бы использовать валидацию по группам)
Для имени:
`@NotBlank(groups = {Create.class})`
Для почты аннотацию `@Email` следует учитываться для обновления и создания, так как, если она не будет передана вообще, то все будет окей, а если будет, тогда она будет проверена на соответствие почте, а вот аннотацию
`@NotEmpty` только для создания) Так как при обновлении передавать ее не обязательно)

Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`. Эта аннотация удобна тем, что допускает null, за счет чего при обновлении по значению мы сможем понять, было передано значение или нет)
Для нее мы сразу укажем две группы: `@Size(groups = {Create.class, Update.class})`, так как она должна быть учтена при создании и обновлении)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
>  public class UserMapper {
(предложение)Можно добавить такую аннотацию
`@NoArgsConstructor(access = AccessLevel.PRIVATE)` или [`@UtilityClass`](https://projectlombok.org/features/experimental/UtilityClass)
Чтобы создать приватный конструктор без параметров, тем самым запретив создание объектов этого класса) Так это не имеет смысла ввиду того, что все в этом классе static, а значит класс не имеет состояния)
Кстати, при использовании второй, даже `static` использовать не потребуется)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/utils/ErrorHandler.java
>  @RestControllerAdvice
Также хорошо было бы передать в лог сообщение об ошибке, а можно и весь трейс, чтобы в случае ошибки было проще разобраться, что именно произошло)
Кстати, при логгировании более эффективно использовать не конкатенацию, а заполнитель - placeholder `{}`
Например:
`log.debug("Получен статус 404 Not found {}", ex.getMessage(), ex);`

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/utils/ErrorHandler.java
> +    public ErrorMessage constraintViolationException(final ConstraintViolationException e) {
Так же можно было бы не создавать для каждого исключения, обрабатываемого как `BAD_REQUEST`, отдельные хендлеры, а собрать их в одну группу в `@ExceptionHandler({ConstraintViolationException.class, IllegalArgumentException.class...})`
А принимаемым аргументом метода-обработчика будет общий класс-наследник - `RuntimeException`.

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
>  public class ItemRequestDto {
Хорошо было бы разбить класс-DTO на несколько, так как, например, при создании нам требуются лишь поле с описанием) Остальные же не требуются. То есть один класс будет использоваться для представления тела запроса, а другой - для представления тела ответа) Таким образом мы будем работать только с теми значениями, что требуются в определенной ситуации

Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    @NotNull
В данном случае следует использовать `@NotBlank`, так как `@NotNull` обезопасит нас только от null, но пустая строка, либо же состоящая только из пробелов - будет принята за корректную

2023-08-22 13:36 UTC, TyutterinYakov commented on src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +public class BookingControllerTest {
Хорошо было бы также добавить тесты на валидацию, где ожидаемым статусом ответа будет 400 BAD_REQUEST)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/test/java/ru/practicum/shareit/controller/ItemControllerTest.java
> +public class ItemControllerTest {
Хорошо было бы также добавить тесты на валидацию, где ожидаемым статусом ответа будет 400 BAD_REQUEST)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/test/java/ru/practicum/shareit/controller/ItemControllerTest.java
> +                        .header("X-Sharer-User-Id", owner.getId()))
Для заголовка у нас введен отдельный класс с константой) Хорошо было бы использовать ее и здесь, чтобы в случае изменений - произвести их лишь в одном месте)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/test/java/ru/practicum/shareit/controller/ItemRequestControllerTest.java
> +public class ItemRequestControllerTest {
Хорошо было бы также добавить тесты на валидацию, где ожидаемым статусом ответа будет 400 BAD_REQUEST)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/test/java/ru/practicum/shareit/controller/UserControllerTest.java
> +public class UserControllerTest {
Хорошо было бы также добавить тесты на валидацию, где ожидаемым статусом ответа будет 400 BAD_REQUEST)
Например, на передачу пользователя на обновление с некорректным форматом почты) Сейчас этот тест не пройдет без предложенной валидации)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImp.java
> +                    List<ItemResponseDto> items = ItemMapper.listItemsToListResponseDto(
Следует получить вещи для всех запросов, которые будут возвращены вне цикла и разбить их на мапу, где ключ - идентификатор запроса, а значение - коллекция из запросов) Таким образом мы не будем производить n-лишних запросов к БД) Получение следует произвести вне цикла)
```
		Map<Long, List<Item>> itemsByRequestId = itemRepository.findByRequestIn(requests)
				.stream()
				.collect(groupingBy(i -> i.getRequest().getId(), toList()));
```
Это лишь предложение по реализации, можно реализовать свою логику, главное избавиться от обращения к методам репозиториев в циклах)

Кстати, потом, при получении из мапы будет удобно использовать метод `getOrDefault`,  чтобы избежать проверок на `null`

Кстати, вместо создания нового объекта класса `ArrayList` в методе `getOrDefault`, можно будет вернуть пустую неизменяемую коллекцию полученную из `List.of()` или `Collections.empty()`

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImp.java
> +                .map(a -> ItemRequestResponseDto.create(a, ItemMapper.listItemsToListResponseDto(
Следует получить вещи для всех запросов, которые будут возвращены вне цикла и разбить их на мапу, где ключ - идентификатор запроса, а значение - коллекция из запросов) Таким образом мы не будем производить n-лишних запросов к БД) Получение следует произвести вне цикла)
```
		Map<Long, List<Item>> itemsByRequestId = itemRepository.findByRequestIn(requests)
				.stream()
				.collect(groupingBy(i -> i.getRequest().getId(), toList()));
```
Это лишь предложение по реализации, можно реализовать свою логику, главное избавиться от обращения к методам репозиториев в циклах)

Кстати, потом, при получении из мапы будет удобно использовать метод `getOrDefault`,  чтобы избежать проверок на `null`

Кстати, вместо создания нового объекта класса `ArrayList` в методе `getOrDefault`, можно будет вернуть пустую неизменяемую коллекцию полученную из `List.of()` или `Collections.empty()`

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestParam(value = "text") @NotBlank String text,
`@NotBlank` не требуется и не будет учтена сейчас, без `@Validated` над классом) Но по ТЗ, при пустой строке - мы не должны выбросить исключение) Мы должны вернуть пустой список)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (text == null || text.trim().isEmpty()) {
Проверка на `null` не имеет смысла, так как параметр запроса является обязательным, так как в `@RequestParam` не указано обратное - `defaultValue = ".."` или `required = false`

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (bookingRepository.findAllByBooker_IdAndItem_IdAndEndBefore(userId, itemId, LocalDateTime.now()).isEmpty()) {
(предложение) Вместо `findBy` можно было бы использовать `exists`, метод репозитория вернет просто значение `true` или `false` в зависимости от того, было найдено значение или нет) Таким образом мы не будет производить ненужную десериализацию, так как нам важно проверить лишь факт наличия)

2023-08-22 13:36 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(this::createItemResponse)
(предложение) Следует получить комментарии всех вещей, которые будут возвращены вне цикла и разбить их на мапу, где ключ - идентификатор вещи, а значение - коллекция из комментариев) Таким образом мы не будем производить n-лишних запросов к БД) Получение следует произвести вне цикла)
Аналогично следует поступить и с поиском предыдущего и следующего бронирования)
Где можно было бы по коллекции предметов произвести получение и сразу же выполнить сортировку, чтобы поиск небходимых бронирований был проще)
```
		Map<Item, List<Comment>> comments = commentRepository.findByItemIn(items, Sort.by(DESC, "created"))
				.stream()
				.collect(groupingBy(Comment::getItem, toList()));
```
Это лишь предложение по реализации, можно реализовать свою логику, главное избавиться от обращения к методам репозиториев в циклах)

2023-08-23 13:32 UTC, TyutterinYakov reviewed
Добрый день! Отметил оставшиеся небольшие недочеты) Хорошего дня! Если возникнут вопросы - пиши в пачку, буду рад помочь🌅

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +    @NotNull(message = "Не указанно время начала бронирования.", groups = {Marker.OnCreate.class})
Аннотация `@notNull` не требуется, так как эта проверка входит в кастомный валидатор) А, так как аннотация для него над классом - валидация будет пройдена раньше)

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +    @NotNull(message = "Не указанно время окончания бронирования.", groups = {Marker.OnCreate.class})
Аннотация `@notNull` не требуется, так как эта проверка входит в кастомный валидатор) А, так как аннотация для него над классом - валидация будет пройдена раньше)

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +    @Future(message = "Время окончания бронирования не должно быть в будущем.")
Также аннотация `@Future` над `end` излишня, так как сначала будет проведена проверка в кастомной валидации, а после мы перейдем к проверке `start`, которая, если удовлетворяет `@FutureOrPresent`, тогда и `end` будет

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>                                @RequestBody ItemDto item) {
Здесь также следует использовать `@Valid`, чтобы аннотации валидации `@Size` стали учтены, так как у них не указана группа)

Но можно было бы использовать:
```
@NotNull(groups = {Marker.OnUpdate.class})
    private Long id;

    @NotBlank(groups = {Marker.OnCreate.class})
    @Size(max = 255, groups = {Marker.OnCreate.class, Marker.OnUpdate.class})
    private String name;
    @NotBlank

    @NotBlank(groups = {Marker.OnCreate.class})
    @Size(max = 512, groups = {Marker.OnCreate.class, Marker.OnUpdate.class})
    private String description;

    @NotNull(groups = {Marker.OnCreate.class})
    private Boolean available;

    private Long requestId;
```

А `@Validated(Marker.OnUpdate.class)` использовать перед параметром `@RequestBody ItemDto item`

Аналогично в других местах) Выше, при создании - будем использовать `@Validated(Marker.OnCreate.class)` вместо `@Valid`

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                         @Valid @RequestBody CommentDto commentDto) {
`@Validated(Marker.OnCreate.class)` более не требуется над методом) Можно использовать сразу вместо `@Valid`

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @Size(max = 255)
`@Size(max = 255, groups = {Marker.OnCreate.class, Marker.OnUpdate.class})`

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @Size(max = 512)
`@Size(max = 512, groups = {Marker.OnCreate.class, Marker.OnUpdate.class})`

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@PathVariable @Positive Long id, @RequestBody @Valid UserDto user) {
`@Validated({Marker.OnUpdate.class})` также не требуется над методом) Можно использовать сразу вместо `@Valid`:
`@Validated({Marker.OnUpdate.class}) @RequestBody UserDto user`

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto saveNewUser(@RequestBody @Valid UserDto user) {
`@Validated({Marker.OnCreate.class})` также не требуется над методом) Можно использовать сразу вместо `@Valid`:
`@Validated({Marker.OnCreate.class}) @RequestBody UserDto user`

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @Size(max = 512)
Здесь также следует указать две группы:
`@Size(max = 512, groups = {Marker.OnCreate.class, Marker.OnUpdate.class})`

2023-08-23 13:32 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @Size(max = 255)
Здесь также следует указать две группы:
`@Size(max = 255, groups = {Marker.OnCreate.class, Marker.OnUpdate.class})`

2023-08-23 15:07 UTC, TyutterinYakov approved these changes
Добрый вечер! Поздравляю с успешной сдачей спринта :) Сил и терпения на этом сложном, но интересном пути! Успехов в обучении и прекрасного вечера!🌃🎇

2023-08-23 15:50 UTC, merged